config/routes.rb
Menu::Application.routes.draw do
  
  resources :prices

  resources :categories

  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  include ActsAsTree
  acts_as_tree order: "name"
  
  has_one :price

  attr_accessible :name, :parent_id

 # validates_inclusion_of :parent_id, :in => , 
 #    :message => "%{value} is not a valid size"

  validates_numericality_of :parent_id, :greater_than => -1 


end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :category_id, :sum

  belongs_to :category
  
  validates :sum, :presence => true 
  validates :category_id , :presence => true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
require 'advice_me'

class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    #@prices = Price.all

    @advice = AdviceMe.random.text
    @advice = @advice.gsub("nbsp;","").gsub('&',"").gsub("#151;","")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @parent = Category.find(@category.parent_id) if @category.parent_id?

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
   
    @parents = [] 
    Category.all.each {|c|   @parents << [c.name, c.id]  }
    @parents << [ "No parent category", 0 ]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
     
    @parents = [] 
    Category.all.each { |c|  @parents << [c.name, c.id] }
    @parents << [ "No parent category", 0 ]
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prices }
    end
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
    @price = Price.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @price }
    end
  end

  # GET /prices/new
  # GET /prices/new.json
  def new
    @price = Price.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @price }
    end
  end

  # GET /prices/1/edit
  def edit
    @price = Price.find(params[:id])
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(params[:price])

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render json: @price, status: :created, location: @price }
      else
        format.html { render action: "new" }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prices/1
  # PUT /prices/1.json
  def update
    @price = Price.find(params[:id])

    respond_to do |format|
      if @price.update_attributes(params[:price])
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price = Price.find(params[:id])
    @price.destroy

    respond_to do |format|
      format.html { redirect_to prices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :parent_id  %><br />
    <%= f.select(:parent_id, @parents )%> 
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table border=1 cellpadding=4>
  <tr>
    <th> id </th>
    <th>Name</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    
    <td align='center'><%= category.name %></td>
    <% category_parent = (@categories.select{ |i| (i.id) == category.parent_id }) %>
    
    <td align='center'> <%= category_parent[0].name unless  category_parent .empty? %></td> 
   
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Category', new_category_path %>
<%= link_to 'Price', prices_path%>  

<p><p><p><p><p><p><p><p><p>       


<h3><font face="verdana"><font size="5"><strong><font color="#3366ff"><%= @advice %> </font></strong></font></font></h3>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Parent:</b>
  <%=  @parent.nil? ? "no parent " : @parent.name  %>
</p>



<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menu</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sum %><br />
    <%= f.text_field :sum %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing prices</h1>

<table border=1 cellpadding = 4 >
  <tr>
    <th>Sum</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prices.each do |price| %>
  <tr>
    <td align='center'><%= price.category.name %></td>
    <td align='center'><%= price.sum %></td>
    <td><%= link_to 'Show', price %></td>
    <td><%= link_to 'Edit', edit_price_path(price) %></td>
    <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<%= link_to 'New Price', new_price_path %>
<%= link_to 'Category List', categories_path %>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sum:</b>
  <%= @price.sum %>
</p>

<p>
  <b>Category:</b>
  <%= @price.category.name %>
</p>


<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>